version: '3'

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy" #/!\ MANDATORY - Define on which network traefik will redirect request
      - "--api.insecure=true"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.ovhresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.ovhresolver.acme.dnschallenge.provider=ovh"
      - "--certificatesresolvers.ovhresolver.acme.dnschallenge.delaybeforecheck=0"
      - "--certificatesresolvers.ovhresolver.acme.email=perso@clfp.fr"
      - "--certificatesresolvers.ovhresolver.acme.storage=/mnt/acme.json"
      - "--serversTransport.insecureSkipVerify=true" #enable https backend with self-signed certificate
      - "--providers.file.filename=/config/tls.yml"
      - "--providers.file.watch=true"
      #LE staging server
#      - "--certificatesresolvers.ovhresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file:
      - "ovh_api.env"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/mnt/swarm/stack-files/01 - proxy/tls.yml:/config/tls.yml"
      - /mnt/swarm/volumes/proxy:/mnt
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.rule=Host(`traefik.clfp.fr`)"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.tls.certresolver=ovhresolver"
        - "traefik.http.routers.traefik.tls.domains[0].main=clfp.fr"
        - "traefik.http.routers.traefik.tls.domains[0].sans=*.clfp.fr"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.HSTS.headers.forcestsheader=true"
        - "traefik.http.middlewares.HSTS.headers.stsincludesubdomains=true"
        - "traefik.http.middlewares.HSTS.headers.stsseconds=31536000"
        - "traefik.http.middlewares.HSTS.headers.sslredirect=true"
        - "traefik.http.routers.traefik.middlewares=HSTS"
