http:
  routers:
    synology-drive:
      entryPoints:
        - websecure
      service: synology
      rule: Host(`drive.clfp.fr`)
      tls:
        certResolver: ovhresolver

  services:
    synology:
      loadBalancer:
        servers:
          - url: "https://nas.dmcn.fr:5000"