entryPoints:
  synology-sync:
    address: ':7766'

http:
  routers:
    synology-drive:
      entryPoints:
        - websecure
      service: synology
      rule: Host(`drive.clfp.fr`) # && (Query(`launchApp=SYNO.SDS.Drive.Application`) || PathPrefix(`/scripts/`) || PathPrefix(`/synoSDSjslib/`) || PathPrefix(`/webapi/`) || PathPrefix(`/webapi/`) || PathPrefix(`/webman/`))
      tls:
        certResolver: ovhresolver

  services:
    synology:
      loadBalancer:
        servers:
          - url: "https://nas.dmcn.fr:10003"

tcp:
  routers:
    synology-sync:
      entryPoints:
        - "synology-sync"
      rule: "HostSNI(`drive.clfp.fr`)"
      service: "synology-sync"
      # will route TLS requests (and ignore non tls requests)
      # tls: {}

  services:
    synology:
      loadBalancer:
        servers:
          - address: "nas.dmcn.fr:6690"