http:
  routers:
    synology-drive:
      entryPoints:
        - websecure
      service: synology
      rule: Host(`drive.clfp.fr`) # && (Query(`launchApp=SYNO.SDS.Drive.Application`) || PathPrefix(`/scripts/`) || PathPrefix(`/synoSDSjslib/`) || PathPrefix(`/webapi/`) || PathPrefix(`/webapi/`) || PathPrefix(`/webman/`))
      tls:
        certResolver: ovhresolver

  services:
    synology:
      loadBalancer:
        servers:
          - url: "https://nas.dmcn.fr:10003"