version: '3'

networks:
  swarm_macvlan:
    external: true

services:
  test:
    image: caddy
    networks:
      - swarm_macvlan
#    ports:
#      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==worker"
