
  
version: '3'

networks:
  proxy:
    external: true

services:
  whoami:
    image: "traefik/whoami"
    networks:
      - proxy
    ports:
      - "8087:80"
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.rule=Host(`whoami.clfp.fr`)"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.tls.certresolver=ovhresolver"
        - "traefik.http.routers.whoami.tls.domains[0].main=clfp.fr"
        - "traefik.http.routers.whoami.tls.domains[0].sans=*.clfp.fr"
