version: '3.2'

networks:
  proxy:
    external: true

services:
  app:
    image: wilply/hugo
    volumes:
      - "./portolio:/app"
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - "node.role == worker"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.entrypoints=websecure"
        - "traefik.http.routers.nextcloud.rule=Host(`portfolio.clfp.fr`)"
        - "traefik.http.routers.nextcloud.tls=true"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=1313"
        - "traefik.http.routers.nextcloud.tls.certresolver=ovhresolver"
        - "traefik.http.routers.nextcloud.middlewares=HSTS"